### ISSUE TITLE
a minor BUG in the PID controller

### ISSUE THREAD

**Issue by Takato20** [utiasDSL/safe-control-gym#128]
I would like to express my gratitude to you and your team for providing such a practical suite!

While reviewing the code in pid.py, I have encountered a possible minor issue. Should the variable 'cur_ang_vel' in line 100 be assigned as 'cur_ang_vel=np.array([0, **obs[5],** 0])' rather than the current assignment of 'np.array([0, **obs[4]**, 0])'?

Could you please check if any modification is necessary?

Also, I was wondering if there are any plans to further improve the CBF controller, which currently seems to only apply to the cartpole system.

I am eagerly looking forward to your future work!

**Comment by Federico-PizarroBejarano** [comment]
@Takato20 concerning the CBF, we do have some ideas about extending it but we have no hard plans currently. There is a PR for a CBF that uses learning (https://github.com/utiasDSL/safe-control-gym/pull/49 implementing this paper: https://arxiv.org/abs/2204.03801), but I believe it also only applies to the cartpole

**Comment by Takato20** [comment]
Thank you for your reply ,and look forward to your future work!
