### ISSUE TITLE
Quadrotor: Craziflie motors corresponding to action dimension. 

### ISSUE THREAD

**Issue by SapanaChaudhary** [utiasDSL/safe-control-gym#143]
Hello! 

The base model for quadrotor is Bitcraze Craziflie 2.0 in the X configuration. 
I was wondering here https://github.com/utiasDSL/safe-control-gym/blob/83fae93172782f7c6e98063da0b2425d3f741f1b/safe_control_gym/envs/gym_pybullet_drones/quadrotor.py#L613
which action dimension corresponds to which motor from the image below? 
<img width="486" alt="Screenshot 2023-10-31 at 5 20 36 PM" src="https://github.com/utiasDSL/safe-control-gym/assets/14027764/b046493f-18b9-4e15-a1a0-9834addbbc64">

**Comment by Federico-PizarroBejarano** [comment]
@JacopoPan @spencerteetaert any idea?

**Comment by JacopoPan** [comment]
Yes, the XY positions of the inputs/motors on the quadrotor are described in the URDF, e.g., see in the lines below that `prop0` is at positive 2.8cm from the center of the quad, in the quad frame, then the others in CCW order.

https://github.com/utiasDSL/safe-control-gym/blob/83fae93172782f7c6e98063da0b2425d3f741f1b/safe_control_gym/envs/gym_pybullet_drones/assets/cf2x.urdf#L40C1-L43

**Comment by SapanaChaudhary** [comment]
Thank you for the reference to the urdf file. 
If the action dimensions are in the same order as prop_links in the urdf file, then action dimensions look like the figure below, as opposed to the figure I had included earlier. 
<img width="468" alt="Screenshot 2023-11-01 at 3 32 46 PM" src="https://github.com/utiasDSL/safe-control-gym/assets/14027764/1905052d-3bb0-463c-9f84-60e195c9507a">
Is this correct?

**Comment by JacopoPan** [comment]
Yes, you can also just look at these lines mapping inputs and the forces/torque in Bullet
https://github.com/utiasDSL/safe-control-gym/blob/83fae93172782f7c6e98063da0b2425d3f741f1b/safe_control_gym/envs/gym_pybullet_drones/base_aviary.py#L392-L406

**Comment by Federico-PizarroBejarano** [comment]
Closing as it seems to have been resolved.
