### ISSUE TITLE
Implementing a Custom Controller on Safe-Control-Gym / Gym-Pybullet Drones 

### ISSUE THREAD

**Issue by lakshmikanth-nageswar** [utiasDSL/safe-control-gym#170]
Hi, could anyone please clear these queries of mine:

- Where exactly in the code is the parameters of System Dynamics (Mass, Inertia, etc) is declared (numerical values)? and is the Dynamics used in training the same as PyBullet Crazyflie (Drone) Dynamics? And could you please tell how to discretise the dynamics (for complete non linear model and linearised dynamics about an equilibrium point)

- How to modify the training tasks say for hover, single set-point (regularisation) and tracking problem through this framework? and for visualisation of trained policy in pybullet as well. (how to modify the BaseAviary or VelocityAviary for tracking and other scripts required to be modified?)

- How to implement our own controller (say linear or non-linear or learning based) in this environment

Thanks in Advance.

**Comment by lakshmikanth-nageswar** [comment]
Hi, Thanks a lot for your response! It is a lot clearer now to implement.

I am excited to implement a Model-based controller that is capable of learning. Could you please tell me on code level how to implement my controller - structure of codebase for model-based controller aided by learning [Say training the controller offline with the params of PyBullet drone and later using it for visualization (or) training it with pose and other state feedback from Pybullet sim]?

I am excited to hear from you.

**Comment by Federico-PizarroBejarano** [comment]
No worries! I am not sure exactly how to help you with your current project. What I would do is take a look at our `examples` folder, especially our RL and MPC examples. If you wanted to make your own controller and own experiments, I would copy an existing controller from the `controllers` folder that is similar to what you are trying to do (for example, PPO for RL or MPC for model-based), modify it, then copy the experiments you want to do from the `examples` folder and modify them to run your controller. You can see how we train an RL controller in the `examples/rl` folder. You can visualize your experiments by passing `gui: True` in the YAML file of your experiments.

**Comment by lakshmikanth-nageswar** [comment]
Thanks a lot for clarification. I'll approach you further if facing any issues. Closing the issue for now.
