### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by farnammn** [utiasDSL/safe-control-gym#28]
Hi,

When I'm installing the package, I get these errors. When I try to install `pycddlib`, I also get similar errors. I have already installed `gmp`, as mentioned in the installation instruction. Do you know what could be the problem, can you please help me?

![Screenshot (32)](https://user-images.githubusercontent.com/41007224/168501698-7c09e67f-f576-4d7e-a8bc-795c238ccb85.png)

![Screenshot (33)](https://user-images.githubusercontent.com/41007224/168501996-1e927fec-fd51-4eb7-82d5-8d605611e015.png)

**Comment by farnammn** [comment]
Hi again, 

I just wanted to use the environments, and I don't need the agents. I don't really need to install the package. Alternatively, can you give me instructions for using the environments in `safe-control-gym/envs` (i.e. the CartPole and Quadrotor class)?

**Comment by JacopoPan** [comment]
Hello @farnammn,

thank you for the interest in the project! The error in the screen captures above does seem related to `gmp`, how did you install it (conda, apt-get)?

For the second point, `examples/verbose_api.py` is an entry point to spin the environments in open loop

Just change
- line 101 in `verbose_api.yaml` to `gui: True`
- line 26 in `verbose_api.py` to `ITERATIONS = int(1000)`

and run
```
python3 verbose_api.py --overrides ./verbose_api.yaml --system quadrotor
```

(You'll need to have `pip3 install -e .` the repo first so if you can't fix your first problem, I suggest to remove the `pytope` dependency from `pyproject.toml`)

**Comment by JacopoPan** [comment]
@amdee 

I think there have been a few issues with the built of `pycddlib` wheel since a commit from a couple of weeks ago
https://github.com/mcmtroffaes/pycddlib/issues/55
But hopefully they are resolved (otherwise we will look for alternative implementations)

**Comment by JacopoPan** [comment]
You might also want to look at this https://github.com/mcmtroffaes/pycddlib/issues/57

**Comment by amdee** [comment]
@JacopoPan Yes, I concur. I completely forgot that I had fixed the issue by reinstalling pycddlib again.
