### ISSUE TITLE
An excellent and comprehensive benchmark. But, the tasks list is desired.

### ISSUE THREAD

**Issue by Jinyi6** [utiasDSL/safe-control-gym#4]
I appreciate such a wonderful benchmark. However, I think that the tasks list is desired.

such as:

https://github.com/openai/safety-gym#benchmark-suite

https://github.com/openai/gym/wiki/Table-of-environments

Thanks~

**Comment by JacopoPan** [comment]
Thanks @Jinyi6 ,

that's a good point: we are currently using a mix of the Gym-style registration system and our own YAML-based configuration system (which has defaults _plus_ overrides, see [safe_control_gym/envs/__init __.py](https://github.com/utiasDSL/safe-control-gym/blob/main/safe_control_gym/envs/__init__.py)).

I will come up with as simple a summary of the configurations I can once we have all the experiments from [this paper](https://arxiv.org/abs/2109.06325) online.
