### ISSUE TITLE
Remove env.gravity

### ISSUE THREAD

**Issue by JakobThumm** [utiasDSL/safe-control-gym#40]
Hi,
I would highly recommend replacing
https://github.com/utiasDSL/safe-control-gym/blob/19ec4f9a6bf7a5c2691aee7c281b0ee255d2e7cc/safe_control_gym/envs/gym_pybullet_drones/quadrotor_utils.py#L107
with just the acceleration that the earth's gravitational force induces on an object `g=9.8 m/s^2`, and calculate `F_g = g * m`, where it's needed.
The word `gravity` has a formal definition and it is very confusing if `env.gravity = 0.2646` instead of `=9.8`!
Thanks,
Jakob

**Comment by JacopoPan** [comment]
Do you still want/plan this change (`GRAVITY` -> `WEIGHT`), @JakobThumm ?
