### ISSUE TITLE
Extend CBF to more systems and extend functionality to guarantee stability

### ISSUE THREAD

**Issue by Federico-PizarroBejarano** [utiasDSL/safe-control-gym#91]
Currently the CBF safety filter only works for the cartpole, and more generally for control affine systems. It should be extended to the other systems in the gym (1D, 2D, and 3D quad). If extended for non-affine systems, we would need to move away from a QP solver. 

Additionally, the CBF can be extended with a CLF to guarantee stabilization.

**Comment by JacopoPan** [comment]
@Federico-PizarroBejarano is any of the on-going PRs addressing this or we should label the issue with "help wanted"?
